sudo: false
language: cpp
compiler: gcc
os:
  - linux
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6

before install:
  - pip install --user cpp-coveralls
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
script:
  - mkdir build && cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - ./test/run_test
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'